In [0]:
# !pip install --upgrade torch torchvision

In [39]:
torch.__version__

'1.3.0'

In [0]:
import torch, torchvision

In [41]:
torch.__version__

'1.3.0'

In [42]:
torch.cuda.get_device_name(0)

'Tesla K80'

In [43]:
torch.cuda.is_available()

True

In [44]:
torch.version.cuda

'10.1.243'

## Using CUDA

In [0]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [46]:
t.shape

torch.Size([2, 3])

In [0]:
t = t.cuda()

In [48]:
t

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

## PyTorch neural network programming

In [0]:
import torch
import numpy as np

In [0]:
t = torch.Tensor()

In [51]:
type(t)

torch.Tensor

### Tensor Attributes

In [52]:
print(t.device)
print(t.dtype)
print(t.layout)

cpu
torch.float32
torch.strided


In [0]:
t = t.cuda()

In [54]:
print(t.device)

cuda:0


In [55]:
type(t)

torch.Tensor

In [0]:
device = torch.device("cuda:0")

In [57]:
device

device(type='cuda', index=0)

In [0]:
data = np.array([1, 2, 3])

In [62]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [63]:
torch.tensor(data)

tensor([1, 2, 3])

In [64]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [65]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [66]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [68]:
torch.zeros(2, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
torch.ones(4, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
torch.cuda.is_available()

True

In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [72]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [74]:
# to see the difference between Constructor and Factory function
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [75]:
torch.get_default_dtype()

torch.float32

In [0]:
data[0] = 0
data[1] = 0
data[2] = 0


In [78]:
# see the difference between different factory function and Tensor constructor
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])
