In [29]:
import torch
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
a = torch.tensor([1, 2, 3])

##### Tensor and Type

In [15]:
torch.typename(a)

'torch.LongTensor'

In [16]:
a

tensor([1, 2, 3])

In [17]:
a.type()

'torch.LongTensor'

In [18]:
a = a.type(torch.FloatTensor)

In [19]:
a

tensor([1., 2., 3.])

In [20]:
# rank of the tensor
a.ndimension()

1

In [21]:
# view method
a.shape

torch.Size([3])

In [22]:
b = a.view(-1, 1)

In [24]:
a.size()

torch.Size([3])

### Functions

In [26]:
x = torch.tensor([0, np.pi/2, np.pi])

In [27]:
torch.sin(x)

tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])

### Sinusoidal Plot

In [41]:
x = torch.linspace(0, 10*np.pi, 100)

In [42]:
y = torch.sin(x)

In [73]:
plt.plot(x.numpy(), y.numpy());

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

## Differential in PyTorch

In [64]:
x = torch.tensor(2., requires_grad=True)

In [57]:
x

tensor(2., requires_grad=True)

In [58]:
y = x**2

In [59]:
y.backward()   #dy(x==2)/dx

In [60]:
x.grad   

tensor(4.)

##### Another Example

In [65]:
z = x**2 + 2*x + 1

In [66]:
z.backward()

In [67]:
x.grad

tensor(6.)

## Partial Derivatives

In [ ]:
u = torch.tensor(1., requires_grad=True)
v = torch.tensor(2., requires_grad=True)

In [74]:
f = u**2 + v**2 + 2*u*v

In [75]:
f.backward()

In [76]:
u.grad

tensor(12.)

In [77]:
v.grad

tensor(12.)