In [0]:
import torch
import numpy as np

In [0]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')


In [0]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [0]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [40]:
print(inputs.shape, targets.shape)

torch.Size([5, 3]) torch.Size([5, 2])


In [0]:
from torch.autograd import Variable

In [0]:
x = Variable(inputs)
y = Variable(targets)

In [0]:
w = torch.randn(y.shape[1], x.shape[1], requires_grad=True)
b = torch.randn(y.shape[1], requires_grad=True)

In [0]:
def model(x):
  return x @ w.t() + b

In [0]:
def mse(y_actual, y_pred):
  diff = y_actual - y_pred
  return torch.sum(diff*diff)/diff.numel()

In [0]:
pred = model(x)

In [68]:
pred

tensor([[176.5707, 137.1729],
        [225.4802, 180.9022],
        [272.4523, 218.5048],
        [189.6696, 130.2217],
        [203.8818, 177.3099]], grad_fn=<AddBackward0>)

In [74]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [0]:
# training the model

for epoch in range(20):
  
  pred = model(x)
  loss = mse(pred, y)
  loss.backward()
  with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    
    w.grad.zero_()
    b.grad.zero_()
    

In [82]:
model(x)

tensor([[ 64.9136,  74.7634],
        [ 79.8325,  99.4703],
        [106.3444, 125.5727],
        [ 70.8922,  63.9429],
        [ 68.8322, 101.7299]], grad_fn=<AddBackward0>)

In [83]:
y

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])