In [0]:
import numpy as np
import torch

In [0]:
import torch.nn as nn

In [0]:
# Input (temp, rainfall, humidity)
inputs = torch.tensor([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype=torch.float32)


# Targets (apples, oranges)
targets = torch.tensor([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype=torch.float32)

In [7]:
print(inputs.shape, targets.shape)

torch.Size([15, 3]) torch.Size([15, 2])


# Dataset and Data Loader
- TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.
- DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [0]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [0]:
dataset = TensorDataset(inputs, targets)

In [0]:
train_gen = DataLoader(dataset, 8, shuffle=True)

In [12]:
for x, y in train_gen:
  print(x.shape, y.shape)
  break

torch.Size([8, 3]) torch.Size([8, 2])


In [0]:
model = nn.Linear(3, 2)

In [18]:
model(inputs)

tensor([[ 54.0886,  61.8167],
        [ 64.8209,  84.6916],
        [ 90.3813, 105.4837],
        [ 59.1094,  48.3616],
        [ 54.8224,  90.2787],
        [ 54.0886,  61.8167],
        [ 64.8209,  84.6916],
        [ 90.3813, 105.4837],
        [ 59.1094,  48.3616],
        [ 54.8224,  90.2787],
        [ 54.0886,  61.8167],
        [ 64.8209,  84.6916],
        [ 90.3813, 105.4837],
        [ 59.1094,  48.3616],
        [ 54.8224,  90.2787]], grad_fn=<AddmmBackward>)

In [19]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [0]:
import torch.nn.functional as F

In [0]:
loss_fn = F.mse_loss

In [23]:
loss_fn(model(inputs), targets)

tensor(682.6704, grad_fn=<MseLossBackward>)

In [0]:
opt = torch.optim.SGD(model.parameters(), 1e-05)

In [0]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_gen:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 1000 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [37]:
fit(10000, model, loss_fn, opt)

Epoch [10/10000], Loss: 1.4982
Epoch [20/10000], Loss: 1.9026
Epoch [30/10000], Loss: 0.9709
Epoch [40/10000], Loss: 0.8611
Epoch [50/10000], Loss: 1.0027
Epoch [60/10000], Loss: 1.3307
Epoch [70/10000], Loss: 1.7748
Epoch [80/10000], Loss: 1.1337
Epoch [90/10000], Loss: 0.6356
Epoch [100/10000], Loss: 1.2199
Epoch [110/10000], Loss: 1.2477
Epoch [120/10000], Loss: 1.3152
Epoch [130/10000], Loss: 0.8787
Epoch [140/10000], Loss: 1.4913
Epoch [150/10000], Loss: 1.0629
Epoch [160/10000], Loss: 0.6861
Epoch [170/10000], Loss: 0.7750
Epoch [180/10000], Loss: 0.9367
Epoch [190/10000], Loss: 1.1683
Epoch [200/10000], Loss: 0.9998
Epoch [210/10000], Loss: 0.7897
Epoch [220/10000], Loss: 0.5330
Epoch [230/10000], Loss: 0.9496
Epoch [240/10000], Loss: 0.7395
Epoch [250/10000], Loss: 0.6289
Epoch [260/10000], Loss: 0.9843
Epoch [270/10000], Loss: 0.6358
Epoch [280/10000], Loss: 0.5885
Epoch [290/10000], Loss: 0.6149
Epoch [300/10000], Loss: 1.2399
Epoch [310/10000], Loss: 0.3887
Epoch [320/10000]

In [36]:
for x, y in train_gen:
  print(model(x), y)
  print(loss_fn(model(x), y))
  break

tensor([[100.3147, 118.6247],
        [120.3383, 133.4784],
        [100.3147, 118.6247],
        [ 57.3306,  70.2976],
        [100.3147, 118.6247],
        [120.3383, 133.4784],
        [ 81.4057, 100.4553],
        [ 21.5492,  37.1658]], grad_fn=<AddmmBackward>) tensor([[103., 119.],
        [119., 133.],
        [103., 119.],
        [ 56.,  70.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.],
        [ 22.,  37.]])
tensor(1.7904, grad_fn=<MseLossBackward>)


In [38]:
for x, y in train_gen:
  print(model(x), y)
  print(loss_fn(model(x), y))
  break

tensor([[118.7318, 132.9535],
        [101.9682, 119.1220],
        [ 57.2518,  70.2584],
        [118.7318, 132.9535],
        [101.9682, 119.1220],
        [ 21.1025,  37.0136],
        [118.7318, 132.9535],
        [ 82.2107, 100.6880]], grad_fn=<AddmmBackward>) tensor([[119., 133.],
        [103., 119.],
        [ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.],
        [119., 133.],
        [ 81., 101.]])
tensor(0.3990, grad_fn=<MseLossBackward>)
