In [0]:
# !pip install --upgrade torch torchvision

In [0]:
# torch.__version__

In [0]:
import torch, torchvision

In [81]:
torch.__version__

'1.2.0'

In [82]:
torch.cuda.get_device_name(0)

'Tesla K80'

In [83]:
torch.cuda.is_available()

True

In [84]:
torch.version.cuda

'10.0.130'

## Using CUDA

In [0]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [86]:
t.shape

torch.Size([2, 3])

In [0]:
t = t.cuda()

In [88]:
t

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

## PyTorch neural network programming

In [0]:
import torch
import numpy as np

In [0]:
t = torch.Tensor()

In [91]:
type(t)

torch.Tensor

### Tensor Attributes

In [92]:
print(t.device)
print(t.dtype)
print(t.layout)

cpu
torch.float32
torch.strided


In [0]:
t = t.cuda()

In [94]:
print(t.device)

cuda:0


In [95]:
type(t)

torch.Tensor

In [0]:
device = torch.device("cuda:0")

In [97]:
device

device(type='cuda', index=0)

In [0]:
data = np.array([1, 2, 3])

In [99]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [100]:
torch.tensor(data)

tensor([1, 2, 3])

In [101]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [102]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [103]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [104]:
torch.zeros(2, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
torch.ones(4, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
torch.cuda.is_available()

True

In [0]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [108]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [109]:
# to see the difference between Constructor and Factory function
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [110]:
torch.get_default_dtype()

torch.float32

In [0]:
data[0] = 0
data[1] = 0
data[2] = 0


In [112]:
# see the difference between different factory function and Tensor constructor
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


## Tensor Operation

-   Reshaping operations
-   Element-wise operations
-   Reduction operations
-   Access operations


In [0]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4],
    [5, 5, 5, 5]
      
], dtype=torch.float32)

In [114]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])

In [115]:
t.size()

torch.Size([5, 4])

In [116]:
t.shape

torch.Size([5, 4])

In [117]:
# components
torch.tensor(t.shape).prod()

tensor(20)

In [118]:
t.numel()

20

In [119]:
t.reshape(10, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.],
        [4., 4.],
        [4., 4.],
        [5., 5.],
        [5., 5.]])

In [120]:
t.squeeze()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])

In [121]:
t.shape

torch.Size([5, 4])

In [122]:
t.squeeze()

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]])

In [0]:
def flatten(t):
  t = t.reshape(1, -1)
  t = t.squeeze()
  return t

In [124]:
flatten(t).shape

torch.Size([20])

In [0]:
t1 = t

In [0]:
t2 = torch.tensor([
    [5, 5, 5, 5],
    [6, 6, 6, 6]
], dtype=torch.float32)

In [0]:
t3 = torch.cat((t1, t2), dim=0)

In [128]:
t3

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.]])

In [0]:
t1 = torch.tensor([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

In [0]:
t2 = torch.tensor([
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2]
])

In [0]:
t3 = torch.tensor([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
])

In [0]:
t = torch.stack((t1, t2, t3), dim = 1)

In [139]:
t.shape

torch.Size([4, 3, 4])